# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\compare_two_scans.ui'
#
# Created: Thu Mar 15 18:08:27 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_compare_two_scans(object):
    def setupUi(self, compare_two_scans):
        compare_two_scans.setObjectName(_fromUtf8("compare_two_scans"))
        compare_two_scans.resize(977, 542)
        compare_two_scans.setStyleSheet(_fromUtf8("QSplitter::handle {\n"
"    border-right: 1px solid darkGray;\n"
"}\n"
"\n"
"QWidget#splitter {\n"
"    border-top: 1px solid darkGray;\n"
"}"))
        self.gridLayout_4 = QtGui.QGridLayout(compare_two_scans)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget = QtGui.QWidget(compare_two_scans)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.searchContainer = QtGui.QWidget(self.widget)
        self.searchContainer.setObjectName(_fromUtf8("searchContainer"))
        self.gridLayout = QtGui.QGridLayout(self.searchContainer)
        self.gridLayout.setMargin(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(0, 8, 0, 8)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.searchContainer)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.searchLineEdit = QtGui.QLineEdit(self.searchContainer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLineEdit.sizePolicy().hasHeightForWidth())
        self.searchLineEdit.setSizePolicy(sizePolicy)
        self.searchLineEdit.setObjectName(_fromUtf8("searchLineEdit"))
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.buttonRescan = QtGui.QPushButton(self.searchContainer)
        self.buttonRescan.setObjectName(_fromUtf8("buttonRescan"))
        self.horizontalLayout.addWidget(self.buttonRescan)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboFiltering = QtGui.QComboBox(self.searchContainer)
        self.comboFiltering.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboFiltering.setObjectName(_fromUtf8("comboFiltering"))
        self.comboFiltering.addItem(_fromUtf8(""))
        self.comboFiltering.addItem(_fromUtf8(""))
        self.comboFiltering.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboFiltering)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBoxAdded = QtGui.QCheckBox(self.searchContainer)
        self.checkBoxAdded.setChecked(True)
        self.checkBoxAdded.setObjectName(_fromUtf8("checkBoxAdded"))
        self.horizontalLayout_2.addWidget(self.checkBoxAdded)
        self.checkBoxChanged = QtGui.QCheckBox(self.searchContainer)
        self.checkBoxChanged.setChecked(True)
        self.checkBoxChanged.setObjectName(_fromUtf8("checkBoxChanged"))
        self.horizontalLayout_2.addWidget(self.checkBoxChanged)
        self.checkBoxRemoved = QtGui.QCheckBox(self.searchContainer)
        self.checkBoxRemoved.setChecked(True)
        self.checkBoxRemoved.setObjectName(_fromUtf8("checkBoxRemoved"))
        self.horizontalLayout_2.addWidget(self.checkBoxRemoved)
        self.checkBoxNotChanged = QtGui.QCheckBox(self.searchContainer)
        self.checkBoxNotChanged.setChecked(True)
        self.checkBoxNotChanged.setObjectName(_fromUtf8("checkBoxNotChanged"))
        self.horizontalLayout_2.addWidget(self.checkBoxNotChanged)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.searchContainer, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFileSystem = QtGui.QWidget()
        self.tabFileSystem.setObjectName(_fromUtf8("tabFileSystem"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabFileSystem)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.treeView = QtGui.QTreeView(self.tabFileSystem)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.treeView.setFrameShadow(QtGui.QFrame.Plain)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.treeView.setProperty("showDropIndicator", False)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeView.setIconSize(QtCore.QSize(16, 16))
        self.treeView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.treeView.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeView.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeView.setIndentation(12)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setSortingEnabled(True)
        self.treeView.setAnimated(True)
        self.treeView.setAllColumnsShowFocus(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.treeView.header().setDefaultSectionSize(100)
        self.treeView.header().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.treeView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabFileSystem, _fromUtf8(""))
        self.tabRegistry = QtGui.QWidget()
        self.tabRegistry.setObjectName(_fromUtf8("tabRegistry"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabRegistry)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.regView = QtGui.QTreeView(self.tabRegistry)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regView.sizePolicy().hasHeightForWidth())
        self.regView.setSizePolicy(sizePolicy)
        self.regView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.regView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.regView.setFrameShadow(QtGui.QFrame.Plain)
        self.regView.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.regView.setProperty("showDropIndicator", False)
        self.regView.setAlternatingRowColors(True)
        self.regView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.regView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.regView.setIconSize(QtCore.QSize(16, 16))
        self.regView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.regView.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.regView.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.regView.setIndentation(12)
        self.regView.setUniformRowHeights(True)
        self.regView.setSortingEnabled(True)
        self.regView.setAnimated(True)
        self.regView.setAllColumnsShowFocus(True)
        self.regView.setObjectName(_fromUtf8("regView"))
        self.regView.header().setDefaultSectionSize(100)
        self.regView.header().setHighlightSections(False)
        self.gridLayout_3.addWidget(self.regView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabRegistry, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(compare_two_scans)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(compare_two_scans)

    def retranslateUi(self, compare_two_scans):
        compare_two_scans.setWindowTitle(QtGui.QApplication.translate("compare_two_scans", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("compare_two_scans", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRescan.setText(QtGui.QApplication.translate("compare_two_scans", "Rescan", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFiltering.setItemText(0, QtGui.QApplication.translate("compare_two_scans", "Show All", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFiltering.setItemText(1, QtGui.QApplication.translate("compare_two_scans", "Only Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFiltering.setItemText(2, QtGui.QApplication.translate("compare_two_scans", "Only Unchecked", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAdded.setText(QtGui.QApplication.translate("compare_two_scans", "Added", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxChanged.setText(QtGui.QApplication.translate("compare_two_scans", "Modified", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxRemoved.setText(QtGui.QApplication.translate("compare_two_scans", "Deleted", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNotChanged.setText(QtGui.QApplication.translate("compare_two_scans", "Not Changed", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFileSystem), QtGui.QApplication.translate("compare_two_scans", "File System Comparison", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegistry), QtGui.QApplication.translate("compare_two_scans", "Registry Comparison", None, QtGui.QApplication.UnicodeUTF8))

