# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\preferences.ui'
#
# Created: Thu Mar 15 18:08:29 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName(_fromUtf8("Preferences"))
        Preferences.resize(756, 538)
        self.gridLayout_2 = QtGui.QGridLayout(Preferences)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(Preferences)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 3)
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFiles = QtGui.QWidget()
        self.tabFiles.setObjectName(_fromUtf8("tabFiles"))
        self.gridLayout = QtGui.QGridLayout(self.tabFiles)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeViewFiles = QtGui.QTreeView(self.tabFiles)
        self.treeViewFiles.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeViewFiles.setUniformRowHeights(False)
        self.treeViewFiles.setSortingEnabled(True)
        self.treeViewFiles.setObjectName(_fromUtf8("treeViewFiles"))
        self.treeViewFiles.header().setSortIndicatorShown(True)
        self.gridLayout.addWidget(self.treeViewFiles, 0, 0, 1, 3)
        self.addFileButton = QtGui.QToolButton(self.tabFiles)
        self.addFileButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addFileButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addFileButton.setProperty("styled", True)
        self.addFileButton.setObjectName(_fromUtf8("addFileButton"))
        self.gridLayout.addWidget(self.addFileButton, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(532, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.deleteFileButton = QtGui.QToolButton(self.tabFiles)
        self.deleteFileButton.setMinimumSize(QtCore.QSize(25, 25))
        self.deleteFileButton.setMaximumSize(QtCore.QSize(25, 25))
        self.deleteFileButton.setProperty("styled", True)
        self.deleteFileButton.setObjectName(_fromUtf8("deleteFileButton"))
        self.gridLayout.addWidget(self.deleteFileButton, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tabFiles, _fromUtf8(""))
        self.tabDirs = QtGui.QWidget()
        self.tabDirs.setObjectName(_fromUtf8("tabDirs"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabDirs)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeViewDirs = QtGui.QTreeView(self.tabDirs)
        self.treeViewDirs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeViewDirs.setSortingEnabled(True)
        self.treeViewDirs.setObjectName(_fromUtf8("treeViewDirs"))
        self.treeViewDirs.header().setSortIndicatorShown(True)
        self.gridLayout_3.addWidget(self.treeViewDirs, 0, 0, 1, 3)
        self.addDirButton = QtGui.QToolButton(self.tabDirs)
        self.addDirButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addDirButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addDirButton.setProperty("styled", True)
        self.addDirButton.setObjectName(_fromUtf8("addDirButton"))
        self.gridLayout_3.addWidget(self.addDirButton, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(532, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.deleteDirButton = QtGui.QToolButton(self.tabDirs)
        self.deleteDirButton.setMinimumSize(QtCore.QSize(25, 25))
        self.deleteDirButton.setMaximumSize(QtCore.QSize(25, 25))
        self.deleteDirButton.setProperty("styled", True)
        self.deleteDirButton.setObjectName(_fromUtf8("deleteDirButton"))
        self.gridLayout_3.addWidget(self.deleteDirButton, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tabDirs, _fromUtf8(""))
        self.tabRegistry = QtGui.QWidget()
        self.tabRegistry.setObjectName(_fromUtf8("tabRegistry"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabRegistry)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.treeViewReg = QtGui.QTreeView(self.tabRegistry)
        self.treeViewReg.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeViewReg.setSortingEnabled(True)
        self.treeViewReg.setObjectName(_fromUtf8("treeViewReg"))
        self.treeViewReg.header().setSortIndicatorShown(True)
        self.gridLayout_4.addWidget(self.treeViewReg, 0, 0, 1, 4)
        self.addRegButton = QtGui.QToolButton(self.tabRegistry)
        self.addRegButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addRegButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addRegButton.setProperty("styled", True)
        self.addRegButton.setObjectName(_fromUtf8("addRegButton"))
        self.gridLayout_4.addWidget(self.addRegButton, 1, 0, 1, 1)
        self.deleteRegButton = QtGui.QToolButton(self.tabRegistry)
        self.deleteRegButton.setMinimumSize(QtCore.QSize(25, 25))
        self.deleteRegButton.setMaximumSize(QtCore.QSize(25, 25))
        self.deleteRegButton.setProperty("styled", True)
        self.deleteRegButton.setObjectName(_fromUtf8("deleteRegButton"))
        self.gridLayout_4.addWidget(self.deleteRegButton, 1, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(532, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabRegistry, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 3)
        self.lblTip = QtGui.QLabel(Preferences)
        self.lblTip.setObjectName(_fromUtf8("lblTip"))
        self.gridLayout_2.addWidget(self.lblTip, 2, 0, 1, 1)
        self.lblExpressionHintLink = QtGui.QLabel(Preferences)
        self.lblExpressionHintLink.setObjectName(_fromUtf8("lblExpressionHintLink"))
        self.gridLayout_2.addWidget(self.lblExpressionHintLink, 2, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 2, 1, 1)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(QtGui.QApplication.translate("Preferences", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Preferences", "The expressions defined here are used to exclude files/directories from the scan.  You can add/remove expressions to customize the scanning process.", None, QtGui.QApplication.UnicodeUTF8))
        self.addFileButton.setToolTip(QtGui.QApplication.translate("Preferences", "Delete the selected scan documents", None, QtGui.QApplication.UnicodeUTF8))
        self.addFileButton.setText(QtGui.QApplication.translate("Preferences", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteFileButton.setToolTip(QtGui.QApplication.translate("Preferences", "Delete the selected scan documents", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteFileButton.setText(QtGui.QApplication.translate("Preferences", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFiles), QtGui.QApplication.translate("Preferences", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.addDirButton.setToolTip(QtGui.QApplication.translate("Preferences", "Delete the selected scan documents", None, QtGui.QApplication.UnicodeUTF8))
        self.addDirButton.setText(QtGui.QApplication.translate("Preferences", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteDirButton.setToolTip(QtGui.QApplication.translate("Preferences", "Delete the selected scan documents", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteDirButton.setText(QtGui.QApplication.translate("Preferences", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDirs), QtGui.QApplication.translate("Preferences", "Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.addRegButton.setToolTip(QtGui.QApplication.translate("Preferences", "Delete the selected scan documents", None, QtGui.QApplication.UnicodeUTF8))
        self.addRegButton.setText(QtGui.QApplication.translate("Preferences", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRegButton.setToolTip(QtGui.QApplication.translate("Preferences", "Delete the selected scan documents", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRegButton.setText(QtGui.QApplication.translate("Preferences", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegistry), QtGui.QApplication.translate("Preferences", "Registry", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTip.setText(QtGui.QApplication.translate("Preferences", "Tip:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblExpressionHintLink.setText(QtGui.QApplication.translate("Preferences", "<a href=\"#expressions\">how to understand and write expressions<a>", None, QtGui.QApplication.UnicodeUTF8))

